#!/usr/bin/env node

/*
 * node-bitplay - Various utilities for playing with Bitcoin with node.js
 * 
 * Copyright (C) 2013 Laurent Eschenauer <laurent@eschenauer.be>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
*/

var bitcoin = require('bitcoin');
var read = require('read');
var config = require('./config.js');

// Initialize the bitcoin client
var client = new bitcoin.Client({
      host: config.host,
      port: config.port,
      user: config.user,
      pass: config.password
});

// Sign a message with the key associated with an account (label)
var sign = function(account, message, callback) {
    client.getAddressesByAccount(account, function(err, addresses) {
          if (err) return callback(err);
          if (addresses.length == 0) return callback(new Error("No address associated to this account (" + account + ")"));
          read({ prompt: 'Passphrase: ', silent: true}, function(er, passphrase) {
            client.walletPassphrase(passphrase, 30, function(err) {
              if (err) return callback(err);
              client.signMessage(addresses[0], message, function(err, signature) {
                if (err) return callback(err);
                client.walletLock(function(err) {
                  callback(null, signature);
                });
              });
            });
          });
    });
}

var main = function(argv) {
        // Parse the command line arguments
        if (argv.length < 3) {
                console.log("Usage: sign account message");
                process.exit(-1);
        }

        // Wrap the request in a try.. catch to nicely die on errors
        try {
                sign(argv[2], argv[3], function(err, result) {
                  if (err) return error(err);
                  console.log("Signature: %s", result);
                }); 
        } catch (error) {
                error(error);
        }
};

var error = function(error) {
      console.log("Error: " + error.message);
      process.exit(-1);
}; 

main(process.argv);
